// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSkh8ThnZRRXKfmE1FD0CQ1QhXAlFHlcI',
    appId: '1:531254605094:web:ad5796317696473dbffde7',
    messagingSenderId: '531254605094',
    projectId: 'cymva-7e984',
    authDomain: 'cymva-7e984.firebaseapp.com',
    storageBucket: 'cymva-7e984.appspot.com',
    measurementId: 'G-4ZSDE6NT6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH_XCsUwIoiOH5bFlC-CMu__Yz-yhgYAY',
    appId: '1:531254605094:android:6a0067de6f2c67c4bffde7',
    messagingSenderId: '531254605094',
    projectId: 'cymva-7e984',
    storageBucket: 'cymva-7e984.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3ZIyLKdO39CS-6XNW2p81RVCnXRL9cWU',
    appId: '1:531254605094:ios:389ee69be8bb41bbbffde7',
    messagingSenderId: '531254605094',
    projectId: 'cymva-7e984',
    storageBucket: 'cymva-7e984.appspot.com',
    iosBundleId: 'com.example.cymva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3ZIyLKdO39CS-6XNW2p81RVCnXRL9cWU',
    appId: '1:531254605094:ios:389ee69be8bb41bbbffde7',
    messagingSenderId: '531254605094',
    projectId: 'cymva-7e984',
    storageBucket: 'cymva-7e984.appspot.com',
    iosBundleId: 'com.example.cymva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSkh8ThnZRRXKfmE1FD0CQ1QhXAlFHlcI',
    appId: '1:531254605094:web:742be2f4e7840b98bffde7',
    messagingSenderId: '531254605094',
    projectId: 'cymva-7e984',
    authDomain: 'cymva-7e984.firebaseapp.com',
    storageBucket: 'cymva-7e984.appspot.com',
    measurementId: 'G-VH1WYKM778',
  );
}
