// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTASyE2E2jcQ24UJbru8A_Jfeo3l1HCMc',
    appId: '1:172950968218:web:a6ba8456c4a4d5da040c23',
    messagingSenderId: '172950968218',
    projectId: 'cymva-595b7',
    authDomain: 'cymva-595b7.firebaseapp.com',
    storageBucket: 'cymva-595b7.appspot.com',
    measurementId: 'G-R29BJX0W2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRgs1qu7a75paojm9Dum7rhWNkuVXs6YM',
    appId: '1:172950968218:android:fc50169d0cd28979040c23',
    messagingSenderId: '172950968218',
    projectId: 'cymva-595b7',
    storageBucket: 'cymva-595b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd1g9LfS7_Gh_AbgJ989-xDQpkt9Zk08U',
    appId: '1:172950968218:ios:6ed3238f603f049a040c23',
    messagingSenderId: '172950968218',
    projectId: 'cymva-595b7',
    storageBucket: 'cymva-595b7.appspot.com',
    iosBundleId: 'com.example.cymva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd1g9LfS7_Gh_AbgJ989-xDQpkt9Zk08U',
    appId: '1:172950968218:ios:6ed3238f603f049a040c23',
    messagingSenderId: '172950968218',
    projectId: 'cymva-595b7',
    storageBucket: 'cymva-595b7.appspot.com',
    iosBundleId: 'com.example.cymva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTASyE2E2jcQ24UJbru8A_Jfeo3l1HCMc',
    appId: '1:172950968218:web:e7e3e548cd5a7473040c23',
    messagingSenderId: '172950968218',
    projectId: 'cymva-595b7',
    authDomain: 'cymva-595b7.firebaseapp.com',
    storageBucket: 'cymva-595b7.appspot.com',
    measurementId: 'G-V6GBKX0P3N',
  );
}
